project:
  type: website
  output-dir: docs

website:
  title: "Ryan Morrow - Data Science Portfolio"
  description: "A showcase of my data science projects and learning journey"
  site-url: "https://rylion9-lgtm.github.io/Portfolio_Morrow_Ryan/"
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.md
      - text: "About Me"
        href: about.md
      - text: "Projects"
        menu:
          - text: "All Projects"
            href: projects/index.md
          - text: "---"
          - text: "Exploratory Data Analysis"
            href: projects/eda.qmd
          - text: "Data Acquisition"
            href: projects/data-acquisition.qmd
          - text: "Final Project"
            href: projects/final-project.qmd
    right:
      - icon: github
        href: https://github.com/your-username
      - icon: linkedin
        href: www.linkedin.com/in/1ryanm1



  sidebar:
    - title: "Projects"
      contents:
        - projects/index.md
        - projects/eda.qmd
        - projects/data-acquisition.qmd
        - projects/final-project.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
